### PR TITLE
Added OutdoorScene

### PR DESCRIPTION
**Pull request by Milind21**
Added Assets (Plane, Fences, Door, Wall, Garden), Renamed Sample Scene to OutdoorScene

### CODE REVIEW

**Review by blst15ki — CHANGES_REQUESTED** [review]
## Required:
- Since you added new assets and we don't have a Source document yet, can you create one with the links to those assets like in our assignments?

## Optional:
- Could you line the fences to be even without overlap and adjust the scene as necessary?
- I'd also prefer if you could organize objects in the scene's hierarchy.

If the optional tasks cannot be completed, I'll add it as an issue to be addressed later.

**Comment by Milind21** [comment]
I will add the src file for the assets today. As for the optional things, I can look into them tomorrow evening. If that doesnt create problem for the code part I will do it tomorrow or else you can add an issue to be adressed after Wednesday.

**Comment by blst15ki** [comment]
It shouldn't create problems for the code if you don't do the optional tasks. It's mainly to make it easier to work with and for aesthetics.

**Comment by Milind21** [comment]
Added src.txt. You can create issue for the optional. I will take a look at them tomorrow.

**Review by blst15ki — APPROVED** [review]

**Pull request merged**
