### PR TITLE
Bryan2

### PR DESCRIPTION
**Pull request by Bn161641**
resize inside scene
make new scene for lobby

### CODE REVIEW

**Review by blst15ki — CHANGES_REQUESTED** [review]
- Character speed is too fast, please change to 10
- Can you add walls or fences to the lobby to prevent the player from walking off the edge for now?
- If possible, try scaling the doors to 2 and scale the scenes accordingly since that's the current scale of the outside scene

**Comment by Bn161641** [comment]
> * Character speed is too fast, please change to 10
> * Can you add walls or fences to the lobby to prevent the player from walking off the edge for now?
> * If possible, try scaling the doors to 2 and scale the scenes accordingly since that's the current scale of the outside scene
I thought we agree on a scale of 1 for the door and the character

**Comment by blst15ki** [comment]
> I thought we agree on a scale of 1 for the door and the character

Yeah you're right, I forgot about that. I will scale the outside door to match then in my PR later

**Comment by blst15ki** [comment]
Sorry, can you add colliders to the objects in the lobby scene as well to prevent the player from walking through the trees and the wagons? I didn't notice that the first time.

Or you can make it such that the player cannot walk back there.

**Comment by blst15ki** [comment]
Not all objects are behind the invisible wall, but I can move them behind it later. Also, is there a reason why you changed the active input handler to use both the old and new input systems?

**Review by blst15ki — APPROVED** [review]

**Pull request merged**
